# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/jactivelte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/jactivelte/proprietary/vendor/bin/mm-qcamera-daemon:system/vendor/bin/mm-qcamera-daemon \
    vendor/samsung/jactivelte/proprietary/vendor/bin/mm-qcamera-app:system/vendor/bin/mm-qcamera-app \
    vendor/samsung/jactivelte/proprietary/vendor/bin/v4l2-qcamera-app:system/vendor/bin/v4l2-qcamera-app \
    vendor/samsung/jactivelte/proprietary/vendor/lib/hw/camera.vendor.msm8960.so:system/vendor/lib/hw/camera.vendor.msm8960.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_imx074_default_video.so:system/vendor/lib/libchromatix_imx074_default_video.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_imx074_preview.so:system/vendor/lib/libchromatix_imx074_preview.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_imx074_video_hd.so:system/vendor/lib/libchromatix_imx074_video_hd.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_imx074_zsl.so:system/vendor/lib/libchromatix_imx074_zsl.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_imx091_default_video.so:system/vendor/lib/libchromatix_imx091_default_video.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_imx091_preview.so:system/vendor/lib/libchromatix_imx091_preview.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_imx091_video_hd.so:system/vendor/lib/libchromatix_imx091_video_hd.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_imx135_video_hdr.so:system/vendor/lib/libchromatix_imx135_video_hdr.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_imx135_zsl.so:system/vendor/lib/libchromatix_imx135_zsl.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_mt9e013_default_video.so:system/vendor/lib/libchromatix_mt9e013_default_video.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_mt9e013_preview.so:system/vendor/lib/libchromatix_mt9e013_preview.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_mt9e013_video_hfr.so:system/vendor/lib/libchromatix_mt9e013_video_hfr.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_ov2720_default_video.so:system/vendor/lib/libchromatix_ov2720_default_video.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_ov2720_hfr.so:system/vendor/lib/libchromatix_ov2720_hfr.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_ov2720_preview.so:system/vendor/lib/libchromatix_ov2720_preview.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_ov2720_zsl.so:system/vendor/lib/libchromatix_ov2720_zsl.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_ov5647_default_video.so:system/vendor/lib/libchromatix_ov5647_default_video.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_ov5647_preview.so:system/vendor/lib/libchromatix_ov5647_preview.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_ov8825_default_video.so:system/vendor/lib/libchromatix_ov8825_default_video.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_ov8825_preview.so:system/vendor/lib/libchromatix_ov8825_preview.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_ov9726_default_video.so:system/vendor/lib/libchromatix_ov9726_default_video.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_ov9726_preview.so:system/vendor/lib/libchromatix_ov9726_preview.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k3h5xa_animation.so:system/vendor/lib/libchromatix_s5k3h5xa_animation.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k3h5xa_antishake.so:system/vendor/lib/libchromatix_s5k3h5xa_antishake.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k3h5xa_default_video.so:system/vendor/lib/libchromatix_s5k3h5xa_default_video.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k3h5xa_lls.so:system/vendor/lib/libchromatix_s5k3h5xa_lls.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k3h5xa_preview.so:system/vendor/lib/libchromatix_s5k3h5xa_preview.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k3h5xa_zsl.so:system/vendor/lib/libchromatix_s5k3h5xa_zsl.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k3h5xa_zsl_drama.so:system/vendor/lib/libchromatix_s5k3h5xa_zsl_drama.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k3h5xa_zsl_panorama.so:system/vendor/lib/libchromatix_s5k3h5xa_zsl_panorama.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k3l1yx_default_video.so:system/vendor/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k3l1yx_preview.so:system/vendor/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k3l1yx_video_hd.so:system/vendor/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k3l1yx_zsl.so:system/vendor/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k4e1_default_video.so:system/vendor/lib/libchromatix_s5k4e1_default_video.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k4e1_preview.so:system/vendor/lib/libchromatix_s5k4e1_preview.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k6b2yx_pip.so:system/vendor/lib/libchromatix_s5k6b2yx_pip.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k6b2yx_preview.so:system/vendor/lib/libchromatix_s5k6b2yx_preview.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k6b2yx_smartstay.so:system/vendor/lib/libchromatix_s5k6b2yx_smartstay.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k6b2yx_video.so:system/vendor/lib/libchromatix_s5k6b2yx_video.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k6b2yx_vt_hd.so:system/vendor/lib/libchromatix_s5k6b2yx_vt_hd.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libchromatix_s5k6b2yx_vt.so:system/vendor/lib/libchromatix_s5k6b2yx_vt.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libgemini.so:system/vendor/lib/libgemini.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libimage-jpeg-enc-omx-comp.so:system/vendor/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libimage-omx-common.so:system/vendor/lib/libimage-omx-common.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmercury.so:system/vendor/lib/libmercury.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmmcamera_frameproc.so:system/vendor/lib/libmmcamera_frameproc.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmmcamera_image_stab.so:system/vendor/lib/libmmcamera_image_stab.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmmcamera_imx091.so:system/vendor/lib/libmmcamera_imx091.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmmcamera_interface2.so:system/vendor/lib/libmmcamera_interface2.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmmcamera_interface.so:system/vendor/lib/libmmcamera_interface.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmmcamera_plugin.so:system/vendor/lib/libmmcamera_plugin.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmmcamera_statsproc31.so:system/vendor/lib/libmmcamera_statsproc31.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmmjpeg_interface.so:system/vendor/lib/libmmjpeg_interface.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmmmpod.so:system/vendor/lib/libmmmpod.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmmstillomx.so:system/vendor/lib/libmmstillomx.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libmmmpo.so:system/vendor/lib/libmmmpo.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libTsAwb.so:system/vendor/lib/libTsAwb.so \
    vendor/samsung/jactivelte/proprietary/vendor/lib/libTsAccm.so:system/vendor/lib/libTsAccm.so 

