# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/jfltexx/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/jf-gsm-common/proprietary/vendor/bin/efsks:system/vendor/bin/efsks \
    vendor/samsung/jf-gsm-common/proprietary/vendor/bin/ks:system/vendor/bin/ks \
    vendor/samsung/jf-gsm-common/proprietary/vendor/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/samsung/jf-gsm-common/proprietary/vendor/bin/qcks:system/vendor/bin/qcks \
    vendor/samsung/jf-gsm-common/proprietary/vendor/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libatparser.so:system/vendor/lib/libatparser.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libfactoryutil.so:system/vendor/lib/libfactoryutil.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libomission_avoidance.so:system/vendor/lib/libomission_avoidance.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libreference-ril.so:system/vendor/lib/libreference-ril.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libril-qcril-external.so:system/vendor/lib/libril-qcril-external.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libsecril-client.so:system/vendor/lib/libsecril-client.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/jf-gsm-common/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so
